development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: shu_development
  pool: 5
  username: shu
  password: '123456'
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: shu_test
  pool: 5
  username: shu
  password: '123456'
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: shu_production
  pool: 5
  username: shu
  password: '123456'
  socket: /var/run/mysqld/mysqld.sock


